import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutSetting from "@/hooks/LayoutSetting";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Starshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const midtransClientKey = process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY || ''; 
  const isProduction = process.env.MIDTRANS_IS_PRODUCTION === 'true';

  const midtransScriptUrl = isProduction 
    ? "https://app.midtrans.com/snap/snap.js"
    : "https://app.sandbox.midtrans.com/snap/snap.js";
  return (
    <html lang="en" className="overscroll-auto scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0f172a]`}
      >
        <LayoutSetting>
        {children}
        {midtransClientKey && (
          <Script 
            src={midtransScriptUrl}
            data-client-key={midtransClientKey}
            strategy="beforeInteractive"
          />
        )}
        </LayoutSetting>
      </body>
    </html>
  );
}
